name: Deploy Bleeding Edge Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/yucling/aihasto-bot:edge